### ISSUE TITLE
Change image content mode in InitialPageViewController from aspect fit to aspect fill

### ISSUE THREAD

**Issue by 3257** [Centroida/SwiftImageCarousel#6]

**Comment by senart** [comment]
Why don't you provide a property for that, so the users can choose the `Content Mode` that best fits their needs?

**Comment by 3257** [comment]
Actually, that is the issue I had now and it would be nice to do just that. I was here to write the issue, but I guess you thought about it too :)

**Comment by 3257** [comment]
Done on OnTapDelegate branch
